// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtB0_ZQ0ANO3OqtpvVIKTT3Ot_IavuEFo',
    appId: '1:581364962777:android:d8f2be418bab252407f5c8',
    messagingSenderId: '581364962777',
    projectId: 'kelimebul-5a4d0',
    storageBucket: 'kelimebul-5a4d0.firebasestorage.app',
    databaseURL: 'https://kelimebul-5a4d0-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpMKZ-enj1mQZYg30MW8o0A2pbdeVaGpU',
    appId: '1:581364962777:ios:00e61dfe51a3344207f5c8',
    messagingSenderId: '581364962777',
    projectId: 'kelimebul-5a4d0',
    storageBucket: 'kelimebul-5a4d0.firebasestorage.app',
    databaseURL: 'https://kelimebul-5a4d0-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.rivorya.kelime',
  );
}
